#!/usr/bin/env bash

SNAP_DIR=/var/lib/snapd

echo "Before cleanup:"
du -sh ${SNAP_DIR}

# Removes old snap revisions
set -eu
LANG=en_US.UTF-8 snap list --all | awk '/disabled/{print $1, $3}' |
    while read snapname revision; do
        snap remove "$snapname" --revision="$revision"
    done

# Clean up the cache
rm -rf /var/lib/snapd/cache/*

echo "After cleanup:"
du -sh ${SNAP_DIR}
